@MusicPlayer.Api_HostAddress = http://localhost:5144

GET {{MusicPlayer.Api_HostAddress}}/api/v1/users
Accept: application/json

{
    ""
}

###

GET {{MusicPlayer.Api_HostAddress}}/api/v1/users/
Accept: application/json

###